#$ home-manager build .[#<name>]
#$ home-manager switch .[#<name>]
{ lib, ... }: with lib.dafitt; {

  dafitt = {
    desktops.common.enable = true;
    desktops.common._1password.enable = true;
    desktops.common.bedtime.enable = true;
    desktops.common.eog.enable = true;
    desktops.common.eog.defaultApplication = true;
    desktops.common.file-roller.enable = true;
    desktops.common.file-roller.defaultApplication = true;
    desktops.common.imv.enable = true;
    desktops.common.kitty.enable = true;
    desktops.common.micro.enable = true;
    desktops.common.mpv.enable = true;
    desktops.common.mpv.defaultApplication = true;
    desktops.common.natuilus.enable = true;
    desktops.common.pcmanfm.enable = true;
    desktops.common.syncthing.enable = true;
    desktops.common.udiskie.enable = true;
    desktops.gnome.enable = true;
    desktops.hyprland.enable = true;
    desktops.hyprland.monitors = [{ name = "DP-1"; primary = true; width = 2560; height = 1440; refreshRate = 120; vrr = 1; bitdepth = 8; x = 0; y = 0; transform = 0; mirror = null; workspace = "1"; }];
    desktops.hyprland.calculator.enable = true;
    desktops.hyprland.cliphist.enable = true;
    desktops.hyprland.fuzzel.enable = true;
    desktops.hyprland.gedit.enable = true;
    desktops.hyprland.hypridle.enable = true;
    desktops.hyprland.hypridle.timeouts.lock = 360;
    desktops.hyprland.hypridle.timeouts.suspend = 600;
    desktops.hyprland.hyprlock.enable = true;
    desktops.hyprland.hyprpaper.enable = true;
    desktops.hyprland.mako.enable = true;
    desktops.hyprland.pavucontrol.enable = true;
    desktops.hyprland.playerctl.enable = true;
    desktops.hyprland.plugins.enable = true;
    desktops.hyprland.swaybg.enable = true;
    desktops.hyprland.swayosd.enable = true;
    desktops.hyprland.top.enable = true;
    desktops.hyprland.waybar.enable = true;
    desktops.hyprland.wlsunset.enable = true;
    development.enableSuite = true;
    development.direnv.enable = true;
    development.git.enable = true;
    development.installExtraPackages = true;
    development.vscode.enable = true;
    development.vscode.defaultApplication = true;
    editing.enableSuite = true;
    editing.installExtraPackages = true;
    flatpak.enable = true;
    gaming.enableSuite = true;
    gaming.installExtraPackages = true;
    gaming.steam.enable = true;
    music.enableSuite = true;
    music.installExtraPackages = true;
    networking.connman.enable = true;
    office.enableSuite = true;
    office.evince.enable = true;
    office.evince.defaultApplication = true;
    office.installExtraPackages = true;
    office.obsidian.enable = true;
    office.scribus.enable = true;
    office.thunderbird.enable = true;
    ricing.enableSuite = true;
    ricing.installExtraPackages = true;
    shells.bash.enable = true;
    shells.fish.enable = true;
    shells.starship.enable = true;
    shells.zsh.enable = true;
    social.enableSuite = true;
    social.installExtraPackages = true;
    virtualizaion.enableSuite = true;
    virtualizaion.installExtraPackages = true;
    virtualizaion.virt-manager.enable = true;
    web.enableSuite = true;
    web.epiphany.enable = true;
    web.installExtraPackages = true;
    web.librewolf.enable = true;
    web.librewolf.defaultApplication = true;
    xdg.enable = true;
    xdg.mimeApps.enable = true;
  };

  home.stateVersion = "23.11";
}
